# Site settings
title: "Den Williams"
description: "CTO / Software Engineer / Technology Enthusiast"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dennis Anthony Williams"
resume_title:                   "CTO / Software Engineer / IT Professional / Technology Enthusiast"
resume_contact_email:
  "work@denwilliams.net"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide (Experience is not shown
# because it is the only required section)
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/denwilliams/"
  resume_twitter_url:           "http://twitter.com/den_williams"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com.au/in/denwilliams"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://denwilliams.net"

# Summary
resume_summary: "This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but K.I.S.S."

# Experience
resume_experience: 
  - role: "CTO"
    company: "LOKE Digital / Aston Club"
    when: "October 2014 - Present"
    summary: "Just a summary"
    competencies:
      - .NET
      - Node.js
      - Android Java
    footnote: Just a footnote
  - role: "Senior Software Engineer"
    company: "Aston Club"
    when: "October 2014 - Present"
  - role: ".NET Developer (Contract)"
    company: "Aston Club"
    when: "Oct 2014 - Present"

# Education
resume_education:
  - where: "University of Technology, Sydney"
    what: "Bachelor of Engineer, Computer Systems"
    when: Jan 1997 - 2003
    notes: "Graduated with first class honours"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
